name: Deploy to Develpoment
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deployment:
    runs-on: 
      group: dikti-runner
    name: deploy development
    steps:
      - name: Build on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USERNAME }}
          password: ${{ secrets.DEV_PASSWORD }}
          port: ${{ secrets.DEV_PORT }}
          script: |
            bash ./deployDev.sh